// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Collation represents a sort ordering for string data.
type Collation struct {
	CollName string // coll_name
}

// PgCollationByOid runs a custom query, returning results as Collation.
func PgCollationByOid(db XODB, oid int) (*Collation, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`collname ` + // ::varchar AS coll_name
		`FROM pg_collation ` +
		`WHERE oid = $1`

	// run query
	XOLog(sqlstr, oid)
	var c Collation
	err = db.QueryRow(sqlstr, oid).Scan(&c.CollName)
	if err != nil {
		return nil, err
	}

	return &c, nil
}
